# Generated by Django 3.1.3 on 2023-02-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230227_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='mark_int',
            new_name='mark',
        ),
    ]
